"""add institution_id column

Revision ID: 6d7cd43b5789
Revises: 
Create Date: 2026-02-21 20:38:30.669817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7cd43b5789'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('affiliation', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('affiliation', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('affiliation', sa.Column('ror', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('affiliation', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('affiliation', sa.Column('affiliation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('affiliation', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_affiliation_external_id'), 'affiliation', ['external_id'], unique=False)
    op.create_index(op.f('ix_affiliation_institution_id'), 'affiliation', ['institution_id'], unique=False)
    op.create_index(op.f('ix_affiliation_organization_id'), 'affiliation', ['organization_id'], unique=False)
    op.create_index(op.f('ix_affiliation_ror'), 'affiliation', ['ror'], unique=False)
    op.create_foreign_key(None, 'affiliation', 'institution', ['institution_id'], ['id'])
    op.add_column('institution', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_institution_source'), table_name='institution')
    op.create_index(op.f('ix_institution_source_id'), 'institution', ['source_id'], unique=False)
    op.create_foreign_key(None, 'institution', 'source', ['source_id'], ['id'])
    op.drop_column('institution', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('source', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'institution', type_='foreignkey')
    op.drop_index(op.f('ix_institution_source_id'), table_name='institution')
    op.create_index(op.f('ix_institution_source'), 'institution', ['source'], unique=False)
    op.drop_column('institution', 'source_id')
    op.drop_constraint(None, 'affiliation', type_='foreignkey')
    op.drop_index(op.f('ix_affiliation_ror'), table_name='affiliation')
    op.drop_index(op.f('ix_affiliation_organization_id'), table_name='affiliation')
    op.drop_index(op.f('ix_affiliation_institution_id'), table_name='affiliation')
    op.drop_index(op.f('ix_affiliation_external_id'), table_name='affiliation')
    op.drop_column('affiliation', 'role')
    op.drop_column('affiliation', 'affiliation_type')
    op.drop_column('affiliation', 'country_code')
    op.drop_column('affiliation', 'ror')
    op.drop_column('affiliation', 'display_name')
    op.drop_column('affiliation', 'external_id')
    op.drop_column('affiliation', 'institution_id')
    # ### end Alembic commands ###
